### ISSUE TITLE
how to test django-treemenus?

### ISSUE THREAD

**Issue by feuervogel** [jphalip/django-treemenus#1]
hi,

I'm using django-treemenus in a project. I've got 'treemenus', 'treemenus.tests' and 'tremenus.tests.fake_menu_extension' in my INSTALLED_APPS. when running the tests, I receive 11 errors for 11 tests, mostly because 

ImportError: No module named fake_menu_extension

how do I have to configure my project to test your app correctly?

**Comment by superbobry** [comment]
@feuervogel, why do you add those `treemenus.*` lines to INSTALLED_APPS? simply adding `treemenus` is enough. have you read django [documentation](http://docs.djangoproject.com/en/1.2/topics/testing/) on testing?

**Comment by feuervogel** [comment]
hi, ok, I've added only the 'treemenus' app to installed_apps. when running

python manage.py test treemenus

I receive an  

ImportError: No module named fake_menu_extension

11 tests, with 11 errors. 

obviously this doesn't work:

```
(bbmain)jmoritz@laptop:~/workspace/bodyboom-main$ python manage.py shell
Python 2.6.5 (r265:79063, Apr 16 2010, 13:57:41) 
[GCC 4.4.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from treemenus.tests import fake_menu_extension
>>> from django.db.models.loading import load_app
>>> from django.conf import settings
>>> settings.INSTALLED_APPS += ['treemenus.tests.fake_menu_extension']
>>> load_app('fake_menu_extension')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/jmoritz/.virtualenvs/bbmain/lib/python2.6/site-packages    
/Django-1.2.3-py2.6.egg/django/db/models/loading.py", line 76, in load_app
    app_module = import_module(app_name)
  File "/home/jmoritz/.virtualenvs/bbmain/lib/python2.6/site-packages/Django-    
1.2.3-py2.6.egg/django/utils/importlib.py", line 35, in import_module

__import__(name)
ImportError: No module named fake_menu_extension
```

**Comment by feuervogel** [comment]
instead, this one works:

```
 >>> load_app('treemenus.tests.fake_menu_extension')
```

seems to be the bugfix for the problem above.

**Comment by jphalip** [comment]
Hello,

So is this ticket resolved?

**Comment by jphalip** [comment]
Oops, never mind, I hadn't seen it was closed already.
