### ISSUE TITLE
Treemenus disappearing under Nginx

### ISSUE THREAD

**Issue by alastc** [jphalip/django-treemenus#12]
I've had a very strange issue with using treemenus in production. It was all going swimmingly well, working great on my local setup with the django-server, but when I moved to the live site it basically disappeared.

On the front-end the templates cause no error, but the output simply does not appear. (I had done a dump-data import-data to get the local menus onto the live site, there should have been something there.)

In the admin section, the menu page would appear fine, but in the change-menu page is blank after the name. The rest of the admin template loads ok, but it's just blank in the middle.

Is treemenu doing anything that Nginx might not like? It is the usual mod_wsgi setup, I haven't had any similar issues with other apps, and I'm a bit stumped as to how to de-bug it.

**Comment by jphalip** [comment]
It looks like the custom admin templates for treemenus aren't loaded/found by Django. I don't see any reason why this wouldn't work specifically under Nginx though...

**Comment by alastc** [comment]
It is the same for the front-end templates as well, it is more than the admin templates.

**Comment by alastc** [comment]
Sorry for the long delay, it's taken a while to get to the next step for this.

I installed what I believe is an identical fastCGI setup locally (baring minor nginx version difference), and don't get the issue.

I installed the django debug bar on the live site (for my ip address only!), but it hasn't helped much. Your are right in that the treemenu specific templates are not loading, and there are no SQL calls for data.

Apart from that, the only difference in debug reporting was the mime type coming through nginx/fastcgi.

I might try updating the production server version of nginx, and I'll check what libraries treemenus uses in case there are bugs in those libraries. Not sure where else to look for the problem.

**Comment by jphalip** [comment]
Have you figured out the root cause of this? I doubt there's anything to do with the application itself, so unless you can provide further details, I'll close the issue. Thanks!

**Comment by alastc** [comment]
Sorry, I've not made any progress. I even installed the debug bar on my live site (for me only), but that didn't provide any clues. I'm going to update nginx and perhaps fastcgi to see if it makes any difference.

**Comment by alastc** [comment]
Updating flup and nginx to the newer debian stable versions solved this. No idea why, but I'm guessing it was some interaction between python (2.5) and flup.
