### ISSUE TITLE
Django 1.4 Admin URL Change

### ISSUE THREAD

**Issue by kingtut** [jphalip/django-treemenus#13]
It looks like [Changeset 16857](https://code.djangoproject.com/changeset/16857/django/trunk/django/contrib/admin/options.py) has broken the app. I get a "Reverse for 'treemenus_menuitem_changelist' with arguments '()' and keyword arguments '{}' not found." when adding a menu item.

**Comment by jphalip** [comment]
Yes, a bit of work is needed to make it work with trunk or the upcoming 1.4. The arrow icons have also been removed from Django and so should be shipped with treemenus.

**Comment by white-hat** [comment]
same problem :(

**Comment by DrMartiner** [comment]
I have problem to: UnboundLocalError at /admin/treemenus/menu/2/items/add/ local variable 'response' referenced before assignment

When you repair this?
