### ISSUE TITLE
Treemenus are not appearing

### ISSUE THREAD

**Issue by stevejbayer** [jphalip/django-treemenus#16]
I had the same issue in https://github.com/jphalip/django-treemenus/issues/13 

I downloaded the latest update today with the fixes (jphalip-django-treemenus-4ed8ad9)

I added the template files as per the packaged documentation (I had some errors due to the online documentation's inaccurate/out of date instructions for coding of the menu template files.)

The site displays without errors (its on a development local machine) but I don't see the tree menus.

If I change the menu name in my template file, I get an error (error: Menu matching query does not exist) and when I enter the correct menu name, the site displays without errors but there is no menu displayed and there is no html mark up for the menus (when the page is viewed through firebug.)

(I only started using Django a couple of days back so I'm afraid I can't look deeper/diagnose the issue deeper.)

**Comment by jphalip** [comment]
Hi, and thanks for the report. Could you please provide the templates that you're using?

**Comment by stevejbayer** [comment]
For learning Django basics, I built a basic site of three pages using flatpages. Here are the template files:

default html template:
http://pastebin.com/A3ybKMCv

menu.html:
http://pastebin.com/1pbFecF4

menu_item.html:
http://pastebin.com/PHZpVjDZ

**Comment by stevejbayer** [comment]
I found out that the issue was that I did not specify whether the menu was to be ordered or unordered in line 12 of my default.html file:
{% show_menu "Navigation" "unordered-list" %}
