### ISSUE TITLE
can't compare offset-naive and offset-aware datetimes

### ISSUE THREAD

**Issue by jw** [jphalip/django-treemenus#17]
On Django 1.4 I've seen this problem.  Could you give me some help?
Thanks,
Jan

Environment:

Request Method: GET
Request URL: http://localhost:8000/

Django Version: 1.4
Python Version: 2.7.3
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.admin',
 'django.contrib.admindocs',
 'django.contrib.markup',
 'elevenbits.blog',
 'elevenbits.static',
 'elevenbits',
 'treemenus',
 'tracking')
Installed Middleware:
('tracking.middleware.BannedIPMiddleware',
 'django.middleware.gzip.GZipMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'tracking.middleware.VisitorTrackingMiddleware')

Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
1.                     response = middleware_method(request)
   File "/usr/local/lib/python2.7/dist-packages/tracking/middleware.py" in process_request
2.         if not visitor.last_update or visitor.last_update <= one_hour_ago:

Exception Type: TypeError at /
Exception Value: can't compare offset-naive and offset-aware datetimes

**Comment by ankitgoyalgithub** [comment]
@jw You can convert timezone aware times to naive. Refer : http://stackoverflow.com/questions/12968565/mongo-objectid-cant-compare-offset-naive-and-offset-aware-datetimes-even-wit
