### ISSUE TITLE
imports fail on django 1.9.4

### ISSUE THREAD

**Issue by ejah** [jphalip/django-treemenus#41]
Encountered following issues when installing tremens in a 1.9.4 site:
in admin.py, importing from django.contrib.admin.util fails. In 1.9.4. this package is django.contrib.admin.utils.

In addition, added AppConfig to apps.py and to init to be compliant with latests changes.

See below GIT file for suggested changes, works for me on 1.9.4. Not tested against older versions. 
Cheers
Ernst

[Suggested_corrections.txt](https://github.com/jphalip/django-treemenus/files/187507/Suggested_corrections.txt)

**Comment by alastc** [comment]
I made a pull request based on this:
https://github.com/jphalip/django-treemenus/pull/43
