### ISSUE TITLE
version numbers in setup.py confuse pip

### ISSUE THREAD

**Issue by 3point2** [jphalip/django-treemenus#5]
i'm using pip to manage dependencies for my project.

it seems like setup.py for django-treemenus 0.8.6 reports its version as 0.8.5, and that setup.py for version 0.8.7 reports its version as 0.8.7-pre.

if i list "django-treemenus==0.8.7" in a requirements file and do "pip install -r requirements.txt". i get the error "Source in [...]/build/django-treemenus has version 0.8.7-pre that conflicts with django-treemenus==0.8.7 (from -r requirements.txt (line 1))"

if i change the requirement to "django-treemenus==0.8.7-pre", i get "No distributions matching the version for django-treemenus==0.8.7-pre (from -r requirements.txt (line 1))"

any chance you could change your version numbers or PyPi index so that they correspond to each other?

**Comment by azumafuji** [comment]
I just added this to the google code issue tracker and then realized the project had moved. This is an issue that has caused us some problems too.  This should be fixed in Pypi asap because it really causes problems with any kind of automated deployment of apps that use django-treemenus.

**Comment by jphalip** [comment]
This should be fixed now (I removed "-pre" from setup.py). Thanks for the report.
