### ISSUE TITLE
named urls doesnt work

### ISSUE THREAD

**Issue by kwevej** [jphalip/django-treemenus#7]
Hello,
named urls does not seem to work.

when pointing to via 'kunden_detail', the generated href is empty...
url(r'^kunden/detail/$', 'abc.views.kunden_detail', name='kunden_detail'),

Thx

**Comment by denizdogan** [comment]
You are probably using the template tag incorrectly. You want to do something like this for menu_item.html:

``` html
{% load tree_menu_tags %}

<li>
  {% if menu_item.url %}
    <a href="{{ menu_item.url }}">{{ menu_item.caption }}</a>
  {% else %}
    <a href="{% reverse_named_url menu_item.named_url %}">{{ menu_item.caption }}</a>
  {% endif %}
</li>
```

**Comment by jphalip** [comment]
My assumption is that @denizdogan is right and that you need to use the {% reverse_named_url %} template tag. So I'll close this issue. Please leave a comment if you do find a bug.
